using UnityEngine;

public class CameraFollow : MonoBehaviour
{
    public Transform target; // El objeto a seguir
    public Vector3 offset; // Desplazamiento de la c치mara respecto al objeto

    void Update()
    {
        if (target != null)
        {
            // Actualizar la posici칩n de la c치mara basada en la posici칩n del target
            transform.position = new Vector3(target.position.x, target.position.y + offset.y, target.position.z + offset.z);
            transform.LookAt(target);
        }
    }

    public void SetTarget(Transform newTarget)
    {
        target = newTarget;
    }
}
